USE [master]
GO

/****** Object:  Database [TheVaddes]    Script Date: 31/03/2023 21:36:35 ******/
CREATE DATABASE [TheVaddes]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'TheVaddes', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\TheVaddes.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'TheVaddes_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\TheVaddes_log.ldf' , SIZE = 73728KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [TheVaddes].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [TheVaddes] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [TheVaddes] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [TheVaddes] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [TheVaddes] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [TheVaddes] SET ARITHABORT OFF 
GO

ALTER DATABASE [TheVaddes] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [TheVaddes] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [TheVaddes] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [TheVaddes] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [TheVaddes] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [TheVaddes] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [TheVaddes] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [TheVaddes] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [TheVaddes] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [TheVaddes] SET  ENABLE_BROKER 
GO

ALTER DATABASE [TheVaddes] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [TheVaddes] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [TheVaddes] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [TheVaddes] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [TheVaddes] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [TheVaddes] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [TheVaddes] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [TheVaddes] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [TheVaddes] SET  MULTI_USER 
GO

ALTER DATABASE [TheVaddes] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [TheVaddes] SET DB_CHAINING OFF 
GO

ALTER DATABASE [TheVaddes] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [TheVaddes] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [TheVaddes] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [TheVaddes] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [TheVaddes] SET QUERY_STORE = OFF
GO

ALTER DATABASE [TheVaddes] SET  READ_WRITE 
GO


